### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Jakedismo** [uber/pyro#1099]
```
(GPUEnv) C:\Users\Joken Surfacebook 2>pip install pyro-ppl
Collecting pyro-ppl
Collecting graphviz>=0.8 (from pyro-ppl)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/05/e4/8fcc76823534d47f079c0ff1b3d8b57784e8fba63ceb1ded32c9f4dd993c/graphviz-0.8.2-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in c:\anaconda\envs\gpuenv\lib\site-packages (from pyro-ppl)
Requirement already satisfied: torch in c:\anaconda\envs\gpuenv\lib\site-packages (from pyro-ppl)
Requirement already satisfied: contextlib2 in c:\anaconda\envs\gpuenv\lib\site-packages (from pyro-ppl)
Exception:
Traceback (most recent call last):
  File "C:\Anaconda\envs\GPUEnv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Anaconda\envs\GPUEnv\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Anaconda\envs\GPUEnv\lib\site-packages\pip\wheel.py", line 756, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Anaconda\envs\GPUEnv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Anaconda\envs\GPUEnv\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "C:\Anaconda\envs\GPUEnv\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "C:\Anaconda\envs\GPUEnv\lib\email\feedparser.py", line 175, in feed
    self._input.push(data)
  File "C:\Anaconda\envs\GPUEnv\lib\email\feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

```
Is this a bug? 
Python 3.6.5
Windows 10

**Comment by fehiepsi** [comment]
@Jakedismo I believe this is a pip issue. Could you update your pip then reinstall?

**Comment by jpchen** [comment]
also windows is not an officially supported platform of pyro, i recommend install PuTTY if you are on windows

**Comment by fritzo** [comment]
Do we need to pin PyTorch version to `torch>=0.4` in our setup.py?

**Comment by neerajprad** [comment]
Closing this issue. Please feel free to post on the [forum](https://forum.pyro.ai/) if you continue to have installation issues.
