### ISSUE TITLE
macOS python 3.6 installation error

### ISSUE THREAD

**Issue by nthakor** [uber/pyro#1100]
I am trying to upgrade pyro in macOS with python 3.6. I am getting following error.

```bash
Collecting pyro
  Using cached https://files.pythonhosted.org/packages/61/68/0978adae315261b87acd216517c2c7f00780396e4d1426c5412458c6a28f/Pyro-3.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w4/mmyv40cx2t32xgqv4gf1chwm0000gn/T/pip-install-beyaqmz_/pyro/setup.py", line 23
        exec code in constants
                ^
    SyntaxError: Missing parentheses in call to 'exec'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w4/mmyv40cx2t32xgqv4gf1chwm0000gn/T/pip-install-beyaqmz_/pyro/

```

**Comment by fehiepsi** [comment]
@nthakor It seems that you install Pyro, not `pyro-ppl`. Use `pip install pyro-ppl` instead.
