### ISSUE TITLE
[bug] Distribution object is not callable

### ISSUE THREAD

**Issue by geffy** [uber/pyro#1303]
Code from tutorial just doesn't work. `pyro.sample("my_sample", dist.Normal(loc, scale))` produces `TypeError: 'Normal' object is not callable`.

### Environment

 - OS: macOS 10.13.5, 
 - Python version: 3.6.5
 - PyTorch version: 0.4.1
 - Pyro version: 0.2.1

### Code Snippet
```python
import torch
import torch.distributions as dist
import pyro

print("torch.__version__: {}".format(torch.__version__))
print("pyro.__version__: {}".format(pyro.__version__))

# code from tutorial http://pyro.ai/examples/intro_part_i.html#Primitive-Stochastic-Functions
loc, scale = 0., 1.
normal = dist.Normal(loc, scale)
x = normal.sample()
print("sample", x)
print("log prob", normal.log_prob(x))

x = pyro.sample("my_sample", dist.Normal(loc, scale))
print(x)%
```

Output:
```python
torch.__version__: 0.4.1
pyro.__version__: 0.2.1
sample tensor(-0.7887)
log prob tensor(-1.2300)
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    x = pyro.sample("my_sample", dist.Normal(loc, scale))
  File "/usr/local/lib/python3.6/site-packages/pyro/primitives.py", line 64, in sample
    return fn(*args, **kwargs)
TypeError: 'Normal' object is not callable
```

**Comment by fritzo** [comment]
You need to import pyro distributions rather than torch distributions:
```py
import pyro.distributions as dist
```
