### ISSUE TITLE
Pyro Installation Error on MacOS

### ISSUE THREAD

**Issue by hakantekgul** [uber/pyro#1386]
I am trying to install pyro through pip, so I run the following command, 
pip install pyro-ppl
After this, I get the following error, What should I do? 
 Downloading https://files.pythonhosted.org/packages/5a/5d/784a147b08d85b00479a4752e5e7341454c6fc1148fe648e98269ba36ded/pyro-ppl-0.2.1.tar.gz (108kB)
    100% |████████████████████████████████| 112kB 891kB/s 
    Complete output from command python setup.py egg_info:
    Failed to convert README.md to rst:
      No module named pypandoc
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-TM1FPt/pyro-ppl/setup.py", line 70, in <module>
        packages=find_packages(include=['pyro', 'pyro.*']),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-TM1FPt/pyro-ppl/

**Comment by hakantekgul** [comment]
I have downloaded pypandoc, but I still get the following error: Collecting pyro-ppl
  Using cached https://files.pythonhosted.org/packages/5a/5d/784a147b08d85b00479a4752e5e7341454c6fc1148fe648e98269ba36ded/pyro-ppl-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-1DqJ8r/pyro-ppl/setup.py", line 70, in <module>
        packages=find_packages(include=['pyro', 'pyro.*']),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-1DqJ8r/pyro-ppl/
