### ISSUE TITLE
Pyro parameters not getting overwritten when a new instance is created

### ISSUE THREAD

**Issue by kiran-kate** [uber/pyro#1488]
DMM example again. When we create a new instance of DMM changing the z_dim and try to run training with the new dmm, I get the following:
```
Traceback (most recent call last):
  File "dmm_pyro.py", line 629, in <module>
    main(args)
  File "dmm_pyro.py", line 578, in main
    which_mini_batch, shuffled_indices)
  File "dmm_pyro.py", line 484, in process_minibatch
    mini_batch_seq_lengths, annealing_factor)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/infer/svi.py", line 75, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/infer/trace_elbo.py", line 107, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, *args, **kwargs):
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/infer/trace_elbo.py", line 54, in _get_traces
    guide_trace = poutine.trace(guide).get_trace(*args, **kwargs)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/poutine/trace_messenger.py", line 202, in get_trace
    self(*args, **kwargs)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/poutine/trace_messenger.py", line 186, in __call__
    ret = self.fn(*args, **kwargs)
  File "dmm_pyro.py", line 236, in guide
    pyro.module("dmm", self)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/primitives.py", line 379, in module
    returned_param = param(full_param_name, param_value)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/primitives.py", line 345, in param
    apply_stack(msg)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/poutine/runtime.py", line 177, in apply_stack
    default_process_message(msg)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/poutine/runtime.py", line 132, in default_process_message
    ret = _PYRO_PARAM_STORE.get_param(name, *args, **kwargs)
  File "<user_home>/anaconda3/lib/python3.6/site-packages/pyro/params/param_store.py", line 112, in get_param
    name, init_tensor.shape, self._params[name].shape))
ValueError: param dmm$$$z_0 init tensor shape does not match existing value: torch.Size([197]) vs torch.Size([100])
```

### Environment
OS and python version: MAC, Python 3.6.5
PyTorch version:0.4.0
Pyro version: 0.2.1

### Code Snippet
I added these lines to the dmm code, main function after the original training loop ends:

```
    # create a new DMM instance
    dmm_new = DMM(rnn_dropout_rate=args.rnn_dropout_rate, num_iafs=args.num_iafs,
              iaf_dim=args.iaf_dim, use_cuda=args.cuda, z_dim=197)

    # setup inference algorithm
    elbo = SVI(dmm_new.model, dmm_new.guide, adam, Trace_ELBO(), trace_graph=False)

    times = [time.time()]
    for epoch in range(args.num_epochs):
        # if specified, save model and optimizer states to disk every checkpoint_freq epochs
        if args.checkpoint_freq > 0 and epoch > 0 and epoch % args.checkpoint_freq == 0:
            save_checkpoint()

        # accumulator for our estimate of the negative log likelihood (or rather -elbo) for this epoch
        epoch_nll = 0.0
        # prepare mini-batch subsampling indices for this epoch
        shuffled_indices = np.arange(N_train_data)
        np.random.shuffle(shuffled_indices)

        # process each mini-batch; this is where we take gradient steps
        for which_mini_batch in range(N_mini_batches):
            epoch_nll += process_minibatch(epoch,
                                           which_mini_batch, shuffled_indices)

        # report training diagnostics
        times.append(time.time())
        epoch_time = times[-1] - times[-2]
        #log("[training epoch %04d]  %.4f \t\t\t\t(dt = %.3f sec)" %
        #    (epoch, epoch_nll / N_train_time_slices, epoch_time))
        log("[training epoch %04d]  %.4f \t\t\t\t(dt = %.3f sec)" %
            (epoch, epoch_nll, epoch_time))

        # Stop when reaching NaN or Inf
        if np.isnan(epoch_nll) or np.isinf(epoch_nll):
            log("Traning failed due to inf or nan")
            return

        # do evaluation on test and validation data and report results
        if epoch > 0 and epoch % args.val_test_frequency == args.val_test_frequency - 1:
            val_nll, test_nll = do_evaluation()
            log("[val/test epoch %04d]  %.4f  %.4f" %
                (epoch, val_nll, test_nll))
```

**Comment by martinjankowiak** [comment]
it seems you're having namespace collisions. please familiarize yourself with how the
pyro [paramstore](http://docs.pyro.ai/en/0.2.1-release/parameters.html#module-pyro.params.param_store) works to resolve your problem.

if you have further issues please post in the forum. as noted below, this is not the intended use for github issues.

> **NOTE:** Issues are for bugs and feature requests only. If you have a question about using Pyro or general modeling questions, please post it on the [forum](https://forum.pyro.ai/).

**Comment by kiran-kate** [comment]
Alright. I forgot to mention that I had tried doing a pyro.clear_param_store() between the two training procedures, which didn't help. I will read through the documentation again to find a way to get this working.

**Comment by jpchen** [comment]
i would recommend setting a breakpoint right before the `pyro.module()` when you instantiate your new instance  and inspect the param store immediately before the exception is thrown. from the looks of it, you're not clearing it.
