### ISSUE TITLE
hmm.py example not working

### ISSUE THREAD

**Issue by tongjiyiming** [uber/pyro#1552]
Just want to run the hmm.py example, and got the following error:
```
      691 Loading data
      722 ----------------------------------------
      722 Training model_1 on 229 sequences
Traceback (most recent call last):
  File "hmm.py", line 295, in <module>
    main(args)
  File "hmm.py", line 244, in main
    guide = AutoDelta(poutine.block(model, expose_fn=lambda msg: msg["name"].startswith("probs_")))
TypeError: block() got an unexpected keyword argument 'expose_fn'
```
look like the function argument is been updated. Then, I changed the "expose_fn" to "expose" as I found in Pyro docs. It still breaks:
```
      682 Loading data
      711 ----------------------------------------
      711 Training model_1 on 229 sequences
Traceback (most recent call last):
  File "hmm.py", line 295, in <module>
    main(args)
  File "hmm.py", line 245, in main
    guide = AutoDelta(poutine.block(model, expose=lambda msg: msg["name"].startswith("probs_")))
  File "/opt/conda/lib/python3.6/site-packages/pyro/poutine/handlers.py", line 209, in block
    hide_types=hide_types, expose_types=expose_types)
  File "/opt/conda/lib/python3.6/site-packages/pyro/poutine/block_messenger.py", line 79, in __init__
    assert set(hide).isdisjoint(set(expose)), \
TypeError: 'function' object is not iterable
```
anyone can check what is the problem?

**Comment by fritzo** [comment]
Hi @tongjiyiming can you verify that your Pyro version matches the example version? I suspect you're using an older Pyro with a newer examples/hmm.py. The example currently works on dev branch.

**Comment by tongjiyiming** [comment]
I got "0.2.1".
So, should I install the dev version?

**Comment by fritzo** [comment]
Yes, the example only works with dev branch for now. We're planning another release in a few weeks, just after PyTorch 1.0 is released.

**Comment by tongjiyiming** [comment]
unfortunately, after I upgrade to dev branch by
```
pip install git+https://github.com/uber/pyro.git#egg=project[extras]
```
It still failed with:
```

**Comment by tongjiyiming** [comment]
Thank you! It works now.
