### ISSUE TITLE
NotImplementedError in examples/ss_vae_M2.py

### ISSUE THREAD

**Issue by jinserk** [uber/pyro#725]
Hi,

I had no error before, but after recent update I got an error when run ss_vae_M2.py as:
```
$ python ss_vae_M2.py -enum
Traceback (most recent call last):
  File "ss_vae_M2.py", line 464, in <module>
    run_inference_ss_vae(args)
  File "ss_vae_M2.py", line 371, in run_inference_ss_vae
    run_inference_for_epoch(data_loaders, losses, periodic_interval_batches)
  File "ss_vae_M2.py", line 268, in run_inference_for_epoch
    new_loss = losses[loss_id].step(xs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/svi.py", line 98, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/elbo.py", line 65, in loss_and_grads
    return self.which_elbo.loss_and_grads(model, guide, *args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/trace_elbo.py", line 146, in loss_and_grads
    for weight, model_trace, guide_trace, log_r in self._get_traces(model, guide, *args, **kwargs):
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/trace_elbo.py", line 79, in _get_traces
    check_enum_discrete_can_run(model_trace, guide_trace)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/trace_elbo.py", line 45, in check_enum_discrete_can_run
    for shape, (source, name) in sorted(shapes.items())])))
NotImplementedError: enum_discrete does not support mixture of batched and un-batched variables. Try rewriting your model to avoid batching or running with enum_discrete=False. Found the following variables of different batch shapes:
guide y: shape = (200,)
guide z: shape = (200, 50)
model x: shape = (200, 784)
```
with `-enum` option. What to do to avoid this?

**Comment by eb8680** [comment]
Hi, what version of PyTorch are you using?  Did you install Pyro from pip or from GitHub?

**Comment by jinserk** [comment]
I'm using Pytorch `0.4.0a0+5b43c22` and Pyro `0.1.2+4d4ffbc`. I've installed them both from each repo.

**Comment by fritzo** [comment]
Thanks for the detailed bug report, @jinserk! This should be fixed by https://github.com/uber/pyro/pull/728

You're welcome to use Pyro dev if you are up for and adventure. We certainly appreciate your help finding bugs as we refactor to use PyTorch distributions.

**Comment by jinserk** [comment]
Thank you for such quick fix, @eb8680 and @fritzo!
By the way, I have another error if `--aux-loss` is on:
```
Traceback (most recent call last):
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/poutine/trace.py", line 81, in log_pdf
    site_log_p = site["log_pdf"]
KeyError: 'log_pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ss_vae_M2.py", line 453, in <module>
    run_inference_ss_vae(args)
  File "ss_vae_M2.py", line 360, in run_inference_ss_vae
    run_inference_for_epoch(data_loaders, losses, periodic_interval_batches)
  File "ss_vae_M2.py", line 254, in run_inference_for_epoch
    new_loss = losses[loss_id].step(xs, ys)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/svi.py", line 98, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/elbo.py", line 65, in loss_and_grads
    return self.which_elbo.loss_and_grads(model, guide, *args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/trace_elbo.py", line 146, in loss_and_grads
    for weight, model_trace, guide_trace, log_r in self._get_traces(model, guide, *args, **kwargs):
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/trace_elbo.py", line 95, in _get_traces
    log_r = model_trace.log_pdf() - guide_trace.log_pdf()
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/poutine/trace.py", line 85, in log_pdf
    site["value"], *args, **kwargs).sum() * site["scale"]
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/distributions/random_primitive.py", line 52, in log_prob
    return self.dist_class(*args, **kwargs).log_prob(x)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/distributions/torch_wrapper.py", line 48, in log_prob
    assert len(self.log_pdf_mask.size()) <= len(log_prob.size())
AttributeError: 'int' object has no attribute 'size'
```

Could you take a look for this too?
