### ISSUE TITLE
RuntimeError: value cannot be converted to type double without overflow: -inf

### ISSUE THREAD

**Issue by lazypanda1** [uber/pyro#876]
THe following program runs into this error:

```
-993.026793856,91.4554859926
Traceback (most recent call last):
  File "progs20180125-225322/prob_rand_997.py", line 49, in <module>
    loss = svi.step(data13945, data13946)
  File "/usr/local/lib/python2.7/dist-packages/pyro/infer/svi.py", line 98, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyro/infer/elbo.py", line 65, in loss_and_grads
    return self.which_elbo.loss_and_grads(model, guide, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyro/infer/trace_elbo.py", line 135, in loss_and_grads
    for weight, model_trace, guide_trace, log_r in self._get_traces(model, guide, *args, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/pyro/infer/trace_elbo.py", line 87, in _get_traces
    log_r = model_trace.log_pdf() - guide_trace.log_pdf()
  File "/usr/local/lib/python2.7/dist-packages/pyro/poutine/trace.py", line 71, in log_pdf
    site["value"], *args, **kwargs) * site["scale"]
  File "/usr/local/lib/python2.7/dist-packages/pyro/distributions/distribution.py", line 185, in log_pdf
    return torch.sum(self.batch_log_pdf(x, *args, **kwargs))
RuntimeError: value cannot be converted to type double without overflow: -inf
```

Code:

```python


import pyro, numpy as np, torch, pyro.distributions as dist, torch.nn as nn
from pyro.optim import Adam
from pyro.infer import SVI
from torch.autograd import Variable
data13945 = np.reshape(np.array([329.69263857473811, -916.64382387967407, 144.17465767235262, 517.82774186895381, -688.49195418050033, 84.850144054131761, -641.40538062017345, 710.5492581786184, 327.03003881957511]), (9, 1))
data13945 =Variable(torch.Tensor(data13945))
data13946 = np.reshape(np.array([-327302.16835565469, 910343.33302071271, -143077.84257760452, -514125.36679159157, 683782.41334119404, -84167.011022263003, 637024.18416493933, -705502.99623955705, -324658.13545746461]), (9, 1))
data13946 =Variable(torch.Tensor(data13946))

class RegressionModel(nn.Module):

    def __init__(self, p):
        super(RegressionModel, self).__init__()
        self.linear = nn.Linear(p, 1)

    def forward(self, x):
        return self.linear(x)
regression_model13947 =RegressionModel(1)

def model(data_x, data_y):
    p13948 = dist.Uniform(
    Variable((897.269264999 * torch.ones((1, 1)))), 
    Variable(((- 569.21712981) * torch.ones((1, 1)))))
    p13949 = dist.Gamma(
    Variable((310.570092601 * torch.ones(1))), 
    Variable((78.929735795 * torch.ones(1))))
    priors13950 =    {'linear.weight': p13948, 'linear.bias': p13949}
    lifted_module13951 =    pyro.random_module('module', regression_model13947, priors13950)
    lifted_reg13952 =    lifted_module13951()
    prediction_mean13953 =    lifted_reg13952(data_x).squeeze()
    pyro.sample('obs', dist.Exponential(
    (torch.nn.Softplus()(prediction_mean13953) * 318.401893075)), obs=    data_y.squeeze())

def guide(data_x, data_y):
    w_mu13954 = Variable(torch.randn(1, 1), requires_grad=True)
    w_log_sig13955 = Variable(torch.randn(1, 1), requires_grad=True)
    b_mu13956 = Variable(torch.randn(1), requires_grad=True)
    b_log_sig13957 = Variable(torch.randn(1), requires_grad=True)
    w_dist = dist.Normal(pyro.param('guide_mean_weight', w_mu13954), torch.nn.Softplus()(pyro.param('guide_log_sigma_weight', w_log_sig13955)))
    b_dist = dist.Normal(pyro.param('guide_mean_bias', b_mu13956), torch.nn.Softplus()(pyro.param('guide_log_sigma_bias', b_log_sig13957)))
    dists = {'linear.weight': w_dist, 'linear.bias': b_dist}
    lifted_module13958 =    pyro.random_module('module', regression_model13947, dists)
    return lifted_module13958()
optim = Adam({'lr': 0.880171324421})
svi = SVI(model, guide, optim, loss='ELBO')
for i in range(311):
    loss = svi.step(data13945, data13946)
    if ((i % 100) == 0):
        print((loss / float(len(data13945))))
for name in pyro.get_param_store().get_all_param_names():
    print(('[%s]: %.3f' % (name, pyro.param(name).data.numpy())))
```

Is this a known bug? Or is there something wrong with the model?

**Comment by eb8680** [comment]
Hi, to avoid `inf`s and `nan`s, you need to use variational distributions with the same support as your priors, and likelihoods where your data lies in the support.

**Comment by fritzo** [comment]
This should be easier to diagnose after https://github.com/pytorch/pytorch/pull/5358 is merged, whereafter you can `torch.distributions.Distribution.set_default_validate_args(True)`. We'll also add something like `pyro.set_validate(True)` to toggle validation of everything (including `torch.distributions`)
