### ISSUE TITLE
DMM Error when using IAFs option

### ISSUE THREAD

**Issue by sameerkhurana10** [uber/pyro#899]
hi,

pyro: '0.1.2'

pytorch: '0.3.1.post2'

when running the DMM example (master branch), on GPU, with the argument `-iafs` set to 1, I get the following error:

```
N_train_data: 229     avg. training seq. length: 60.29    N_mini_batches: 12
Traceback (most recent call last):
  File "dmm.py", line 436, in <module>
    main(args)
  File "dmm.py", line 396, in main
    epoch_nll += process_minibatch(epoch, which_mini_batch, shuffled_indices)
  File "dmm.py", line 356, in process_minibatch
    mini_batch_seq_lengths, annealing_factor)
  File "/data/sls/u/sameerk/anaconda3/envs/nova-gpu-pytold/lib/python3.5/site-packages/pyro/infer/svi.py", line 98, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/data/sls/u/sameerk/anaconda3/envs/nova-gpu-pytold/lib/python3.5/site-packages/pyro/infer/elbo.py", line 65, in loss_and_grads
    return self.which_elbo.loss_and_grads(model, guide, *args, **kwargs)
  File "/data/sls/u/sameerk/anaconda3/envs/nova-gpu-pytold/lib/python3.5/site-packages/pyro/infer/trace_elbo.py", line 133, in loss_and_grads
    for weight, model_trace, guide_trace, log_r in self._get_traces(model, guide, *args, **kwargs):
  File "/data/sls/u/sameerk/anaconda3/envs/nova-gpu-pytold/lib/python3.5/site-packages/pyro/infer/trace_elbo.py", line 83, in _get_traces
    check_model_guide_match(model_trace, guide_trace)
  File "/data/sls/u/sameerk/anaconda3/envs/nova-gpu-pytold/lib/python3.5/site-packages/pyro/util.py", line 373, in check_model_guide_match
    guide_shape = guide_site["fn"].shape(None, *guide_site["args"], **guide_site["kwargs"])
  File "/data/sls/u/sameerk/anaconda3/envs/nova-gpu-pytold/lib/python3.5/site-packages/pyro/distributions/distribution.py", line 149, in shape
    return self.batch_shape(x, *args, **kwargs) + self.event_shape(*args, **kwargs)
  File "/data/sls/u/sameerk/anaconda3/envs/nova-gpu-pytold/lib/python3.5/site-packages/pyro/distributions/transformed_distribution.py", line 62, in event_shape
    return self.base_dist.batch_shape(*args, **kwargs)
  File "/data/sls/u/sameerk/anaconda3/envs/nova-gpu-pytold/lib/python3.5/site-packages/pyro/distributions/random_primitive.py", line 25, in batch_shape
    return self.dist_class(*args, **kwargs).batch_shape(x)
TypeError: __init__() missing 1 required positional argument: 'sigma'
srun: error: sls-titan-0: task 0: Exited with exit code 1

```

**Comment by martinjankowiak** [comment]
@sameerkhurana10 
i'm not sure what issue you're running into but i verified that this works in pyro dev. so if you'd like to run the model i suggest you either use pyro dev (see here for installation: https://github.com/uber/pyro/blob/dev/README.md) or wait a few works for the pyro 0.2 release.
