### ISSUE TITLE
latest dev docs broken 

### ISSUE THREAD

**Issue by jpchen** [uber/pyro#964]
```
/home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/checkouts/dev/docs/source/contrib.gp.rst:6: WARNING: autodoc: failed to import module u'pyro.contrib.gp'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/envs/dev/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/checkouts/dev/pyro/__init__.py", line 14, in <module>
    import pyro.infer as infer
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/checkouts/dev/pyro/infer/__init__.py", line 9, in <module>
    from pyro.infer.advi import ADVI, ADVIMultivariateNormal, ADVIDiagonalNormal
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/checkouts/dev/pyro/infer/advi.py", line 16, in <module>
    from contextlib2 import ExitStack  # python 2
ImportError: No module named contextlib2
/home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/checkouts/dev/docs/source/contrib.gp.rst:15: WARNING: autodoc: failed to import module u'pyro.contrib.gp.models.model'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/envs/dev/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/checkouts/dev/pyro/__init__.py", line 13, in <module>
    import pyro.distributions as dist
AttributeError: 'module' object has no attribute 'distributions'
```

may possibly be from #961 and/or #951. can we error on these warnings in travis? because the docs build succeeds even if exceptions are thrown.

**Comment by fritzo** [comment]
:+1: to erroring if doc build fails

**Comment by fritzo** [comment]
Yes this was from #951. We probably need to add `pip install contextlib2` to the docs build dependency
